# This is a basic workflow that is manually triggered

name: Convert resume.md to resume.pdf

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - 'main'
    paths:
      - docs/resume.md

jobs:
  my_first_job:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: clone to-pdf
      uses: actions/checkout@v3
      with:
        repository: briansobodacha/to-pdf
        token: ${{ secrets.ACCESS_TOKEN }}
        path: ./to-pdf
    - name: install requirements
      run: pip install -r to-pdf/requirements.txt
    - name: exec to-pdf
      run: python to-pdf/to-pdf.py ./docs/resume.md
    - name: mv pdf
      run: mv -f to-pdf/a.pdf docs/resume.pdf
    - name: commit pdf
      uses: EndBug/add-and-commit@v9
      with:
        committer_name: GitHub Actions
        committer_email: 41898282+github-actions[bot]@users.noreply.github.com
        message: 'Update resume.pdf'
        add: 'docs/resume.pdf'