# This is a basic workflow that is manually triggered

name: Convert resume.md to resume.pdf

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - 'main'
    paths:
      - docs/resume.md'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my_first_job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Setup Python Version
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 # Install the python version needed
    - name: clone
      uses: actions/checkout@v3
      with:
        repository: briansobodacha/to-pdf
        token: ${{ secrets.ACCESS_TOKEN }}
        path: ./to-pdf
    - name: install requirements
      run: pip install -r to-pdf/requirements.txt
    - name: convert
      run: python to-pdf/to-pdf.py ./docs/resume.md
    - name: mv
      run: mv -f to-pdf/a.pdf docs/resume.pdf
    - name: commit changes
      uses: EndBug/add-and-commit@v9
      with:
        committer_name: GitHub Actions
        committer_email: 41898282+github-actions[bot]@users.noreply.github.com
        message: 'Update resume.pdf'
        add: 'docs/resume.pdf'