# This is a basic workflow that is manually triggered

name: Convert resume.md to resume.pdf

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - 'main'
    paths:
      - '**/**.md'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my_first_job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: env
      run: env | sort
    - name: clone
      run: git clone git@github.com:briansobodacha/to-pdf.git
    - name: ls
      run: ls -AFoh
    - name: Send greeting
      run: python -c "print('Hello friend')"
